# Description: List of object classes generated by ChatGPT or directly taken from ScanNet. 

scannet_objects = ["wall", "chair", "floor", "table", "door", "couch", "cabinet", "shelf", "desk", "office chair", "bed", 
    "pillow", "sink", "picture", "window", "toilet", "bookshelf", "monitor", "curtain", "book", "armchair", "coffee table", 
    "box", "refrigerator", "lamp", "kitchen cabinet", "towel", "clothes", "tv", "nightstand", "counter", "dresser", "stool", 
    "cushion", "plant", "ceiling", "bathtub", "end table", "dining table", "keyboard", "bag", "backpack", "toilet paper", 
    "printer", "tv stand", "whiteboard", "blanket", "shower curtain", "trash can", "closet", "stairs", "microwave", "stove", 
    "shoe", "computer tower", "bottle", "bin", "ottoman", "bench", "board", "washing machine", "mirror", "copier", "basket", 
    "sofa chair", "file cabinet", "fan", "laptop", "shower", "paper", "person", "paper towel dispenser", "oven", "blinds", 
    "rack", "plate", "blackboard", "piano", "suitcase", "rail", "radiator", "recycling bin", "container", "wardrobe", 
    "soap dispenser", "telephone", "bucket", "clock", "stand", "light", "laundry basket", "pipe", "clothes dryer", "guitar", 
    "toilet paper holder", "seat", "speaker", "column", "bicycle", "ladder", "bathroom stall", "shower wall", "cup", "jacket", 
    "storage bin", "coffee maker", "dishwasher", "paper towel roll", "machine", "mat", "windowsill", "bar", "toaster", 
    "bulletin board", "ironing board", "fireplace", "soap dish", "kitchen counter", "doorframe", "toilet paper dispenser", 
    "mini fridge", "fire extinguisher", "ball", "hat", "shower curtain rod", "water cooler", "paper cutter", "tray", 
    "shower door", "pillar", "ledge", "toaster oven", "mouse", "toilet seat cover dispenser", "furniture", "cart", 
    "storage container", "scale", "tissue box", "light switch", "crate", "power outlet", "decoration", "sign", "projector", 
    "closet door", "vacuum cleaner", "candle", "plunger", "stuffed animal", "headphones", "dish rack", "broom", "guitar case", 
    "range hood", "dustpan", "hair dryer", "water bottle", "handicap bar", "purse", "vent", "shower floor", "water pitcher", 
    "mailbox", "bowl", "paper bag", "alarm clock", "music stand", "projector screen", "divider", "laundry detergent", 
    "bathroom counter", "object", "bathroom vanity", "closet wall", "laundry hamper", "bathroom stall door", "ceiling light", 
    "trash bin", "dumbbell", "stair rail", "tube", "bathroom cabinet", "cd case", "closet rod", "coffee kettle", "structure", 
    "shower head", "keyboard piano", "case of water bottles", "coat rack", "storage organizer", "folded chair", "fire alarm", 
    "power strip", "calendar", "poster", "potted plant", "luggage", "mattress"]

kitchen_objects = [  # Not solely kitchen objects, but a mix of kitchen, bathroom, and living room objects
    'sink', 'faucet', 'oven', 'stove', 'refrigerator', 'freezer', 'microwave', 'toaster', 'blender', 'mixer',
    'kettle', 'coffee machine', 'dishwasher', 'trash can', 'recycling bin', 'countertop', 'cupboard', 'drawer', 'plate', 'bowl',
    'cup', 'glass', 'mug', 'knife', 'fork', 'spoon', 'chopsticks', 'teapot', 'cutting board', 'colander', 'strainer',
    'can opener', 'peeler', 'grater', 'measuring cup', 'measuring spoon', 'rolling pin', 'cookie jar', 'pot', 'pan',
    'baking sheet', 'cake tin', 'frying pan', 'saucepan', 'wok', 'skillet', 'roasting pan', 'slow cooker', 'pressure cooker',
    'air fryer', 'rice cooker', 'steamer', 'grill', 'microwaveable bowl', 'wine opener', 'cocktail shaker', 'spatula',
    'whisk', 'tongs', 'ladle', 'pasta spoon', 'basting brush', 'meat thermometer', 'tea strainer', 'corkscrew', 'strainer',
    'mortar and pestle', 'blender bottle', 'salt shaker', 'pepper grinder', 'sugar bowl', 'honey jar', 'jam jar',
    'kitchen timer', 'sugar container', 'flour container', 'breadbox', 'cookie cutter', 'egg holder', 'bottle opener',
    'cooling rack', 'cheese grater', 'canister', 'spice rack', 'spice jar', 'hot pad', 'oven mitt', 'dish towel',
    'paper towel holder', 'sink strainer', 'dish rack', 'trash bag', 'recycling bin lid', 'compost bin', 'ice cube tray',
    'ice cream scooper', 'garbage disposal', 'dish soap', 'hand soap', 'scrub brush', 'scrub sponge', 'dustpan', 'broom',
    'vacuum cleaner', 'mop', 'bucket', 'floor cleaner', 'window cleaner', 'toilet brush', 'toilet paper holder',
    'bathroom sink', 'shower', 'bathtub', 'towel rack', 'bath mat', 'soap dish', 'shampoo bottle', 'conditioner bottle',
    'toothpaste', 'toothbrush', 'razor', 'comb', 'hair dryer', 'bathrobe', 'loofah', 'shower curtain', 'mirror',
    'medicine cabinet', 'first aid kit', 'trash bin', 'bath towel', 'hand towel', 'washcloth', 'tissue box', 'plunger',
    'air freshener', 'humidifier', 'dehumidifier', 'fan', 'space heater', 'air purifier', 'light bulb', 'lamp',
    'ceiling fan', 'wall sconce', 'night light', 'outlet', 'extension cord', 'power strip', 'tv remote', 'television',
    'television stand', 'soundbar', 'speakers', 'dvd player', 'game console', 'gaming controller', 'computer',
    'laptop', 'tablet', 'smartphone', 'charging cable', 'charger', 'wireless charger', 'phone case', 'headphones',
    'earbuds', 'keyboard', 'mouse', 'monitor', 'printer', 'scanner', 'external hard drive', 'flash drive', 'SD card',
    'printer paper', 'notebook', 'pen', 'pencil', 'highlighter', 'stapler', 'paper clips', 'sticky notes', 'envelopes',
    'scissors', 'tape', 'glue stick', 'glue gun', 'hole puncher', 'rubber bands', 'clipboard', 'ruler', 'calendar',
    'picture frame', 'art print', 'painting', 'poster', 'mirror', 'wall clock', 'candle', 'vase', 'flower pot',
    'plant', 'plant pot', 'book', 'magazine', 'newspaper', 'board game', 'puzzle', 'card game', 'playing cards',
    'chess set', 'poker chips', 'bowtie', 'scarf', 'hat', 'coat hanger', 'clothes dryer', 'clothes iron', 'ironing board',
    'laundry basket', 'laundry detergent', 'fabric softener', 'dryer sheets', 'stain remover', 'clothes pins',
    'clothes rack', 'trolley', 'shower shelf', 'toilet cleaner', 'bath sponge', 'pool towels', 'shower cap', 'sponge',
    'cleaning cloth', 'bottle brush', 'spout brush', 'oven cleaner', 'stovetop cleaner', 'bath cleaner', 'floor mop',
    'dusting cloth', 'scrubbing pad', 'cleaning gloves', 'disinfectant', 'bleach', 'floor mat', 'door mat', 'shoe rack',
    'shoes', 'boots', 'slippers', 'laundry hamper', 'toilet seat', 'door handle', 'drawer pull', 'cabinet knob',
    'window blind', 'curtain', 'shade', 'curtain rod', 'towel bar', 'bath tray', 'shower organizer', 'toilet paper',
    'bath towel', 'laundry detergent', 'fabric softener', 'dryer balls', 'wash basket', 'dresser', 'wardrobe', 'closet',
    'bookshelf', 'lamp shade', 'floor lamp', 'coffee table', 'side table', 'end table', 'bookshelf', 'cushion', 'pillow',
    'throw blanket', 'area rug', 'dining table', 'coffee mug', 'fork', 'spoon', 'butter dish', 'salt shaker', 'soup spoon',
    'dessert fork', 'dinner plate', 'side plate', 'salad bowl', 'tablecloth', 'placemat', 'coasters', 'serving tray'
]

office_objects = [  # Not solely office objects, but a mix of office, home, and tech objects
    'mouse', 'keyboard', 'monitor', 'desk', 'chair', 'office chair', 'laptop', 'desktop computer', 'printer', 'scanner',
    'telephone', 'fax machine', 'paper shredder', 'file cabinet', 'bookshelf', 'books', 'notebook', 'pen', 'pencil',
    'highlighter', 'stapler', 'staples', 'paper clips', 'binder', 'paper', 'sticky notes', 'post-it notes', 'envelopes',
    'folder', 'clipboard', 'hole punch', 'rubber bands', 'tape dispenser', 'scissors', 'ruler', 'calculator', 'calendar',
    'sticky tabs', 'desk lamp', 'light bulb', 'ceiling light', 'wall clock', 'whiteboard', 'blackboard', 'dry erase marker',
    'chalk', 'chalkboard eraser', 'paper tray', 'wastebasket', 'trash can', 'recycling bin', 'mouse pad', 'monitor stand',
    'document holder', 'printer paper', 'ink cartridge', 'toner', 'thumb drive', 'USB cable', 'HDMI cable', 'power strip',
    'extension cord', 'surge protector', 'smartphone', 'tablet', 'charging cable', 'wireless charger', 'charging dock',
    'headphones', 'headset', 'microphone', 'webcam', 'video conference camera', 'phone charger', 'wall outlet', 'router',
    'modem', 'network cable', 'USB hub', 'external hard drive', 'hard drive', 'flash drive', 'SD card', 'earbuds', 'dock',
    'server rack', 'file organizer', 'letter opener', 'clipboard holder', 'desk organizer', 'drawer', 'drawer organizer',
    'pen holder', 'pen cup', 'tissue box', 'document scanner', 'printer tray', 'laser pointer', 'whiteboard eraser',
    'magnifying glass', 'file folder', 'address label', 'postage meter', 'stamps', 'catalog', 'business card holder',
    'name tag', 'name plate', 'plant', 'plant pot', 'umbrella stand', 'coat rack', 'coat hanger', 'doormat', 'shoe rack',
    'storage bin', 'luggage', 'coffee mug', 'water bottle', 'thermos', 'travel mug', 'file box', 'office binder',
    'label maker', 'chalk holder', 'desk drawer', 'paper cutter', 'letter tray', 'post-it holder', 'calculator stand',
    'printer stand', 'receipt holder', 'wrist rest', 'bookend', 'magnets', 'push pins', 'paper towel holder', 'mug rack',
    'book light', 'laser printer', 'photocopier', 'fax paper', 'carbon paper', 'label sheet', 'printer ink', 'office safe',
    'whiteboard magnets', 'sticky note dispenser', 'notepad', 'pouch', 'calculator cover', 'monitor mount', 'projector',
    'projector screen', 'projection remote', 'conference phone', 'conference table', 'speakerphone', 'standing desk',
    'desk riser', 'file organizer tray', 'trash bag', 'vacuum cleaner', 'broom', 'dustpan', 'air purifier', 'air freshener',
    'humidifier', 'dehumidifier', 'space heater', 'cooling fan', 'floor mat', 'desk mat', 'ergonomic chair mat', 'file folder',
    'CD holder', 'DVD holder', 'file divider', 'desk clock', 'digital clock', 'printer stand', 'tape measure', 'office sign',
    'post-it dispenser', 'corkboard', 'magnet board', 'punch bowl', 'tea kettle', 'coffee machine', 'coaster', 'notebook stand',
    'letter tray holder', 'contact book', 'briefcase', 'backpack', 'file binder', 'portfolio', 'folder divider', 'conference pad',
    'clipboard stand', 'carpet', 'window blinds', 'shades', 'curtain rod', 'curtain', 'trash bin lid', 'recycling bin lid',
    'shelving unit', 'desk drawer organizer', 'shoe mat', 'office binder', 'memo pad', 'paper clip holder', 'battery charger',
    'keyboard tray', 'monitor arm', 'printer drawer', 'mobile phone stand', 'pencil case', 'pen tray', 'office chair mat',
    'outlet strip', 'USB power bank', 'USB extension cord', 'wall socket', 'audio speakers', 'standing lamp', 'hanging light',
    'tablet stand', 'phone stand', 'book display', 'document holder', 'multiport charger', 'desk divider', 'partition',
    'printer stand', 'file organizer basket', 'storage chest', 'storage drawer', 'archive box', 'letter tray organizer',
    'index cards', 'large clipboard', 'trolley', 'storage cabinet', 'office planner', 'motion sensor light', 'personal fan',
    'tablet stand', 'tablet holder', 'folding chair', 'adjustable desk', 'recliner', 'workspace divider', 'furniture pad',
    'work lamp', 'meeting table', 'drawer pull', 'storage box', 'USB drive holder', 'electronic lock', 'laptop sleeve', 'pocket organizer'
]

# specific_objects = ["robot", "robot arm", "microwave door", "microwave body", "balloon", "cabinet door"]
specific_objects = ["robot", "robot arm", "microwave body", "balloon", "cabinet door", "eggs"]
# specific_objects = ["robot", "robot arm", "balloon", "cabinet door"]

# Combine all object classes
# object_classes = scannet_objects + kitchen_objects + office_objects + specific_objects
object_classes = scannet_objects + specific_objects  # The kitchen and office objects are too specific

# Remove duplicates
object_classes = list(set(object_classes))

# Sort object classes
object_classes.sort()

print(f"Total number of object classes: {len(object_classes)}")


if __name__ == "__main__":
    import json
    import random

    # Save object classes to a .txt file. Sorted alphabetically and one class per line.
    with open("conceptgraph/custom_classes.txt", "w") as file:
        for obj_class in object_classes:
            file.write(obj_class + "\n")

    # Save object classes to a .json file with the class name as key and a random 
    # RGB color (in the interval [0, 1]) as value. Sorted alphabetically.
    object_classes_dict = {obj_class: [random.random(), random.random(), random.random()] for obj_class in object_classes}
    
    with open("conceptgraph/custom_classes_colors.json", "w") as file:
        json.dump(object_classes_dict, file, indent=4)
